version: 2
jobs:
  build:
    working_directory: ~/pollsapi
    docker:
      # specify the version you desire here
      - image: circleci/python:3.6.1

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"

      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            cd pollsapi
            python manage.py tes

      - store_artifacts:
          path: test-reports
          destination: test-reports

